# Generated by Django 5.0.5 on 2024-05-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_purchaseorder_issue_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='time_delivery',
        ),
        migrations.AddField(
            model_name='vendor',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
